#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Meter_Replacement.Resource", IsApplication=true)]

namespace Meter_Replacement
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int button1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int button2 = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int editText1 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReplacementData = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int ApplicationName = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int Hello = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int default_web_client_id = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int firebase_database_url = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int gcm_defaultSenderId = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int google_api_key = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int google_app_id = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int google_crash_reporting_api_key = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int google_storage_bucket = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
